### ISSUE TITLE
Difference between classes

### ISSUE THREAD

**Issue by PinkQween** [xxOliveXyzxx/japanesegame#2]
I see 2 classes what are the differences?

**Comment by vOlive-io** [comment]
I am coding an app to teach Japanese, these are the classes that me and my friends mare making lesson plans for! If u want me to teach u thu, I can try

**Comment by PinkQween** [comment]
Thanks, do you mean next Thursday or is it too late?

**Comment by vOlive-io** [comment]
Like after i finish this
